name: whiteboardkit
description: An whiteboard tool.
version: 1.0.0
homepage: https://www.uparty.top/
repository: https://github.com/ggdream/whiteboardkit

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  xml: ^5.1.2
  synchronized: ^3.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
